/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as ReglasRouteImport } from './routes/reglas'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as VenderRouteImport } from './routes/vender'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as OrdenesIndexRouteImport } from './routes/ordenes.index'
import { Route as OrdenesIdRouteImport } from './routes/ordenes.$id'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as UIdRouteImport } from './routes/u.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglasRoute = ReglasRouteImport.update({
  id: '/reglas',
  path: '/reglas',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const VenderRoute = VenderRouteImport.update({
  id: '/vender',
  path: '/vender',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OrdenesIndexRoute = OrdenesIndexRouteImport.update({
  id: '/ordenes/',
  path: '/ordenes/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdenesIdRoute = OrdenesIdRouteImport.update({
  id: '/ordenes/$id',
  path: '/ordenes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UIdRoute = UIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categorias': typeof CategoriasRoute
  '/favoritos': typeof FavoritosRoute
  '/marketplace': typeof MarketplaceRoute
  '/nosotros': typeof NosotrosRoute
  '/privacidad': typeof PrivacidadRoute
  '/reglas': typeof ReglasRoute
  '/terminos': typeof TerminosRoute
  '/tienda': typeof TiendaRoute
  '/transparencia': typeof TransparenciaRoute
  '/vender': typeof VenderRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/ordenes/$id': typeof OrdenesIdRoute
  '/p/$id': typeof PIdRoute
  '/u/$id': typeof UIdRoute
  '/ordenes/': typeof OrdenesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categorias': typeof CategoriasRoute
  '/favoritos': typeof FavoritosRoute
  '/marketplace': typeof MarketplaceRoute
  '/nosotros': typeof NosotrosRoute
  '/privacidad': typeof PrivacidadRoute
  '/reglas': typeof ReglasRoute
  '/terminos': typeof TerminosRoute
  '/tienda': typeof TiendaRoute
  '/transparencia': typeof TransparenciaRoute
  '/vender': typeof VenderRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/ordenes/$id': typeof OrdenesIdRoute
  '/p/$id': typeof PIdRoute
  '/u/$id': typeof UIdRoute
  '/ordenes': typeof OrdenesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/categorias': typeof CategoriasRoute
  '/favoritos': typeof FavoritosRoute
  '/marketplace': typeof MarketplaceRoute
  '/nosotros': typeof NosotrosRoute
  '/privacidad': typeof PrivacidadRoute
  '/reglas': typeof ReglasRoute
  '/terminos': typeof TerminosRoute
  '/tienda': typeof TiendaRoute
  '/transparencia': typeof TransparenciaRoute
  '/vender': typeof VenderRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/ordenes/$id': typeof OrdenesIdRoute
  '/p/$id': typeof PIdRoute
  '/u/$id': typeof UIdRoute
  '/ordenes/': typeof OrdenesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/categorias'
    | '/favoritos'
    | '/marketplace'
    | '/nosotros'
    | '/privacidad'
    | '/reglas'
    | '/terminos'
    | '/tienda'
    | '/transparencia'
    | '/vender'
    | '/perfil'
    | '/ordenes/$id'
    | '/p/$id'
    | '/u/$id'
    | '/ordenes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/categorias'
    | '/favoritos'
    | '/marketplace'
    | '/nosotros'
    | '/privacidad'
    | '/reglas'
    | '/terminos'
    | '/tienda'
    | '/transparencia'
    | '/vender'
    | '/perfil'
    | '/ordenes/$id'
    | '/p/$id'
    | '/u/$id'
    | '/ordenes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/categorias'
    | '/favoritos'
    | '/marketplace'
    | '/nosotros'
    | '/privacidad'
    | '/reglas'
    | '/terminos'
    | '/tienda'
    | '/transparencia'
    | '/vender'
    | '/_authenticated/perfil'
    | '/ordenes/$id'
    | '/p/$id'
    | '/u/$id'
    | '/ordenes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CategoriasRoute: typeof CategoriasRoute
  FavoritosRoute: typeof FavoritosRoute
  MarketplaceRoute: typeof MarketplaceRoute
  NosotrosRoute: typeof NosotrosRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ReglasRoute: typeof ReglasRoute
  TerminosRoute: typeof TerminosRoute
  TiendaRoute: typeof TiendaRoute
  TransparenciaRoute: typeof TransparenciaRoute
  VenderRoute: typeof VenderRoute
  OrdenesIdRoute: typeof OrdenesIdRoute
  PIdRoute: typeof PIdRoute
  UIdRoute: typeof UIdRoute
  OrdenesIndexRoute: typeof OrdenesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglas': {
      id: '/reglas'
      path: '/reglas'
      fullPath: '/reglas'
      preLoaderRoute: typeof ReglasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vender': {
      id: '/vender'
      path: '/vender'
      fullPath: '/vender'
      preLoaderRoute: typeof VenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/ordenes/': {
      id: '/ordenes/'
      path: '/ordenes'
      fullPath: '/ordenes/'
      preLoaderRoute: typeof OrdenesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordenes/$id': {
      id: '/ordenes/$id'
      path: '/ordenes/$id'
      fullPath: '/ordenes/$id'
      preLoaderRoute: typeof OrdenesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$id': {
      id: '/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof UIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CategoriasRoute: CategoriasRoute,
  FavoritosRoute: FavoritosRoute,
  MarketplaceRoute: MarketplaceRoute,
  NosotrosRoute: NosotrosRoute,
  PrivacidadRoute: PrivacidadRoute,
  ReglasRoute: ReglasRoute,
  TerminosRoute: TerminosRoute,
  TiendaRoute: TiendaRoute,
  TransparenciaRoute: TransparenciaRoute,
  VenderRoute: VenderRoute,
  OrdenesIdRoute: OrdenesIdRoute,
  PIdRoute: PIdRoute,
  UIdRoute: UIdRoute,
  OrdenesIndexRoute: OrdenesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
