/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as VenderRouteImport } from './routes/vender'
import { Route as OrdenesIndexRouteImport } from './routes/ordenes.index'
import { Route as OrdenesIdRouteImport } from './routes/ordenes.$id'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as UIdRouteImport } from './routes/u.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const VenderRoute = VenderRouteImport.update({
  id: '/vender',
  path: '/vender',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdenesIndexRoute = OrdenesIndexRouteImport.update({
  id: '/ordenes/',
  path: '/ordenes/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdenesIdRoute = OrdenesIdRouteImport.update({
  id: '/ordenes/$id',
  path: '/ordenes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UIdRoute = UIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/favoritos': typeof FavoritosRoute
  '/marketplace': typeof MarketplaceRoute
  '/perfil': typeof PerfilRoute
  '/tienda': typeof TiendaRoute
  '/vender': typeof VenderRoute
  '/ordenes/$id': typeof OrdenesIdRoute
  '/p/$id': typeof PIdRoute
  '/u/$id': typeof UIdRoute
  '/ordenes/': typeof OrdenesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/favoritos': typeof FavoritosRoute
  '/marketplace': typeof MarketplaceRoute
  '/perfil': typeof PerfilRoute
  '/tienda': typeof TiendaRoute
  '/vender': typeof VenderRoute
  '/ordenes/$id': typeof OrdenesIdRoute
  '/p/$id': typeof PIdRoute
  '/u/$id': typeof UIdRoute
  '/ordenes': typeof OrdenesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/favoritos': typeof FavoritosRoute
  '/marketplace': typeof MarketplaceRoute
  '/perfil': typeof PerfilRoute
  '/tienda': typeof TiendaRoute
  '/vender': typeof VenderRoute
  '/ordenes/$id': typeof OrdenesIdRoute
  '/p/$id': typeof PIdRoute
  '/u/$id': typeof UIdRoute
  '/ordenes/': typeof OrdenesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categorias'
    | '/favoritos'
    | '/marketplace'
    | '/perfil'
    | '/tienda'
    | '/vender'
    | '/ordenes/$id'
    | '/p/$id'
    | '/u/$id'
    | '/ordenes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categorias'
    | '/favoritos'
    | '/marketplace'
    | '/perfil'
    | '/tienda'
    | '/vender'
    | '/ordenes/$id'
    | '/p/$id'
    | '/u/$id'
    | '/ordenes'
  id:
    | '__root__'
    | '/'
    | '/categorias'
    | '/favoritos'
    | '/marketplace'
    | '/perfil'
    | '/tienda'
    | '/vender'
    | '/ordenes/$id'
    | '/p/$id'
    | '/u/$id'
    | '/ordenes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriasRoute: typeof CategoriasRoute
  FavoritosRoute: typeof FavoritosRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PerfilRoute: typeof PerfilRoute
  TiendaRoute: typeof TiendaRoute
  VenderRoute: typeof VenderRoute
  OrdenesIdRoute: typeof OrdenesIdRoute
  PIdRoute: typeof PIdRoute
  UIdRoute: typeof UIdRoute
  OrdenesIndexRoute: typeof OrdenesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vender': {
      id: '/vender'
      path: '/vender'
      fullPath: '/vender'
      preLoaderRoute: typeof VenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordenes/': {
      id: '/ordenes/'
      path: '/ordenes'
      fullPath: '/ordenes/'
      preLoaderRoute: typeof OrdenesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordenes/$id': {
      id: '/ordenes/$id'
      path: '/ordenes/$id'
      fullPath: '/ordenes/$id'
      preLoaderRoute: typeof OrdenesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$id': {
      id: '/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof UIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriasRoute: CategoriasRoute,
  FavoritosRoute: FavoritosRoute,
  MarketplaceRoute: MarketplaceRoute,
  PerfilRoute: PerfilRoute,
  TiendaRoute: TiendaRoute,
  VenderRoute: VenderRoute,
  OrdenesIdRoute: OrdenesIdRoute,
  PIdRoute: PIdRoute,
  UIdRoute: UIdRoute,
  OrdenesIndexRoute: OrdenesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
